[package]
name = "rust-neuralnet"
version = "0.0.1"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]

[dependencies]
rand = "0.8.4"
ndarray = "0.15.3"

[dev-dependencies]
approx = "0.5.0"
